### ISSUE TITLE
Saved model cluttered with buffers

### ISSUE THREAD

**Issue by Atcold** [lim0606/torch-inception-resnet-v2#4]
The model you saved and put on Google Drive is `7.2G`.
You should run

``` lua
net:clearState()
net:float()
```

Then, your model will be `242M`.

**Comment by lim0606** [comment]
@Atcold 

Thank you for your comment :)

I'm re-training the model w/ debugged version as I commented in (https://github.com/facebook/fb.resnet.torch/pull/64)

I will update it as you commented. 

Thanks!
